/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Sms.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Sms.Controller.BatchController;
import lk.ijse.Sms.Controller.CoursesController;
import lk.ijse.Sms.Modal.Batches;
import lk.ijse.Sms.Modal.Courses;

/**
 *
 * @author Rukz
 */
public class AddBatches extends javax.swing.JPanel {

    /**
     * Creates new form AddBatches
     */
    public AddBatches() {
        initComponents();
        
        loadCourseId();
        genarateBatchID();
        loadAllBatches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBatchNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmbcid = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblBatch = new javax.swing.JTable();
        txtRfresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CID  (course ID)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));

        txtBid.setBackground(java.awt.Color.white);
        txtBid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBid.setForeground(new java.awt.Color(0, 0, 0));
        txtBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBidActionPerformed(evt);
            }
        });
        add(txtBid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 40));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BID (batch ID)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        txtBatchNum.setBackground(java.awt.Color.white);
        txtBatchNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBatchNum.setForeground(new java.awt.Color(0, 0, 0));
        add(txtBatchNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 40));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BATCH NUMBER");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 30));

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 120, 40));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 120, 40));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 120, 40));

        cmbcid.setBackground(java.awt.Color.white);
        cmbcid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbcid.setForeground(new java.awt.Color(0, 0, 0));
        add(cmbcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 40));

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Add  Batches");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jtblBatch.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtblBatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch ID", "Course ID", "Batch Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblBatch);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 490, 180));

        txtRfresh.setBackground(new java.awt.Color(211, 84, 0));
        txtRfresh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRfresh.setForeground(new java.awt.Color(0, 0, 0));
        txtRfresh.setText("REFRESH");
        txtRfresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfreshActionPerformed(evt);
            }
        });
        add(txtRfresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 110, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-ok-50.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 50, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-delete-50.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 50, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-synchronize-45.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         try {
            
            String bid=txtBid.getText();
            String cid= cmbcid.getSelectedItem().toString();
            String batchNum=txtBatchNum.getText();
           

             Batches b1=new Batches(bid, cid, batchNum);
           
            
            boolean isSaved=new BatchController().saveBatches(b1);
            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved");
            }else{
                JOptionPane.showMessageDialog(null,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBidActionPerformed
       if(txtBid.getText().trim().length()>0){
            try {
              
                Batches OBj;
                OBj = new BatchController().getBatches(txtBid.getText().trim());

                if(OBj!=null){
                    
                     cmbcid.setSelectedItem(OBj.getCid());
                     txtBatchNum.setText(OBj.getBatch_num());
                     

                }else{
                    JOptionPane.showMessageDialog(this,"No Results Fount","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if(txtBid.getText().trim().length()>0){
            try {
               
                String bid=txtBid.getText();
                String cid= cmbcid.getSelectedItem().toString();
                String batch_num=txtBatchNum.getText();

                
              
                
                Batches b1=new Batches(bid, cid, batch_num);

                if(new BatchController().updateBatch(b1)){
                    JOptionPane.showMessageDialog(null,"Success");
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Please Insert An BID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtBid.getText().trim().length()>0){

            try {
                if(new BatchController().dropBatch(txtBid.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Deleted");
                }else{
                    JOptionPane.showMessageDialog(null,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please insert an BID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtRfreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfreshActionPerformed
        try {
            List<Batches> SubjectList= new BatchController().getAllBatches();
            DefaultTableModel modal=(DefaultTableModel) jtblBatch.getModel();
            modal.setRowCount(0);
            for(Batches sub:SubjectList){
                Object[] rowData={
                    sub.getBid(),
                    sub.getCid(),
                    sub.getBatch_num()};
                modal.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    }//GEN-LAST:event_txtRfreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblBatch;
    private javax.swing.JTextField txtBatchNum;
    private javax.swing.JTextField txtBid;
    private javax.swing.JButton txtRfresh;
    // End of variables declaration//GEN-END:variables

    private void loadCourseId() {
        try {
            ArrayList<Courses> AllCourses=CoursesController.getAllCourses();
            for(Courses course:AllCourses){
                cmbcid.addItem(course.getCid());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }

    private void genarateBatchID() {
         try {
            String BatchID = BatchController.generateBatchID();
            txtBid.setText(BatchID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllBatches() {
        try {
            List<Batches> BatchList= new BatchController().getAllBatches();
            DefaultTableModel modal=(DefaultTableModel)jtblBatch.getModel();
            for(Batches tempBatch:BatchList){
                
                modal.addRow(new Object[]{
                    
                    tempBatch.getBid(),
                    tempBatch.getCid(),
                    tempBatch.getBatch_num(),
                    
                    
                
                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
