/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Sms.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Sms.Controller.PaymentController;
import lk.ijse.Sms.Controller.RegistrationController;
import lk.ijse.Sms.Modal.Payments;
import lk.ijse.Sms.Modal.Registration;

/**
 *
 * @author Rukz
 */
public class AddPayments extends javax.swing.JPanel {

    /**
     * Creates new form AddPayments
     */
    public AddPayments() {
        initComponents();
        loadREGID();
        genaratePid();
        
        Date date = new Date();
        String formatDate = formatDate(date);
        txtDate.setText(formatDate);
        
        loadAllPayments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbRid = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPayingAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRemainingAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPayment = new javax.swing.JTable();
        txtRfresh = new javax.swing.JButton();
        btnpay = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RID  (Registration ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, 30));

        txtPid.setBackground(java.awt.Color.white);
        txtPid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPid.setForeground(new java.awt.Color(0, 0, 0));
        txtPid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPidActionPerformed(evt);
            }
        });
        add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 40));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PID (Payment ID)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        cmbRid.setBackground(java.awt.Color.white);
        cmbRid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbRid.setForeground(new java.awt.Color(0, 0, 0));
        add(cmbRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 210, 40));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DATE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));

        txtDate.setBackground(java.awt.Color.white);
        txtDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 40));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TOTAL  AMOUNT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 130, 30));

        txtTotalAmount.setBackground(java.awt.Color.white);
        txtTotalAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTotalAmount.setForeground(new java.awt.Color(0, 0, 0));
        add(txtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 210, 40));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PAYING  AMOUNT");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 30));

        txtPayingAmount.setBackground(java.awt.Color.white);
        txtPayingAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPayingAmount.setForeground(new java.awt.Color(0, 0, 0));
        txtPayingAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayingAmountActionPerformed(evt);
            }
        });
        add(txtPayingAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REMAINING  AMOUNT");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 130, 30));

        txtRemainingAmount.setBackground(java.awt.Color.white);
        txtRemainingAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRemainingAmount.setForeground(new java.awt.Color(0, 0, 0));
        add(txtRemainingAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 210, 40));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DETAILS");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 30));

        txtDetails.setBackground(java.awt.Color.white);
        txtDetails.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDetails.setForeground(new java.awt.Color(0, 0, 0));
        add(txtDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 540, 40));

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 110, 40));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 110, 40));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 110, 40));

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Add  Payments");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        jtblPayment.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Registration ID", "Date", "Total Amount", "Paying Amount", "Remaining Amount", "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblPayment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 900, 190));

        txtRfresh.setBackground(new java.awt.Color(211, 84, 0));
        txtRfresh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRfresh.setForeground(new java.awt.Color(0, 0, 0));
        txtRfresh.setText("REFRESH");
        txtRfresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfreshActionPerformed(evt);
            }
        });
        add(txtRfresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 110, 40));

        btnpay.setBackground(new java.awt.Color(211, 84, 0));
        btnpay.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnpay.setForeground(new java.awt.Color(0, 0, 0));
        btnpay.setText("Click to get Remaining Payment");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-ok-50.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 50, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-delete-50.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 50, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-synchronize-45.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        try {
            String pid=txtPid.getText();
            String rid=cmbRid.getSelectedItem().toString();
            String pdate=txtDate.getText();
            String total_amount=txtTotalAmount.getText();
            String paying_amount=txtPayingAmount.getText();
            String remaining_payment=txtRemainingAmount.getText();
            String detail=txtDetails.getText();

            Payments p1=new Payments(pid, rid, pdate, total_amount, paying_amount, remaining_payment, detail);
           
            boolean isSaved=new PaymentController().savePayment(p1);
            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved");
            }else{
                JOptionPane.showMessageDialog(null,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddPayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPidActionPerformed
        if(txtPid.getText().trim().length()>0){
            try {
              
                Payments OBj;
                OBj = new PaymentController().getPayment(txtPid.getText().trim());

                if(OBj!=null){
                     
                     cmbRid.setSelectedItem(OBj.getRid());
                     txtDate.setText(OBj.getPdate());
                     txtTotalAmount.setText(OBj.getTotal_amount());
                     txtPayingAmount.setText(OBj.getPaying_amount());
                     txtRemainingAmount.setText(OBj.getRemaining_payment());
                     txtDetails.setText(OBj.getDetail());

                }else{
                    JOptionPane.showMessageDialog(this,"No Results Fount","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtPid.getText().trim().length()>0){

            try {
                if(new PaymentController().dropPayment(txtPid.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Deleted");
                }else{
                    JOptionPane.showMessageDialog(null,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please insert an PID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txtPid.getText().trim().length()>0){
            try {
               
               String pid=txtPid.getText();
            String rid=cmbRid.getSelectedItem().toString();
            String pdate=txtDate.getText();
            String total_amount=txtTotalAmount.getText();
            String paying_amount=txtPayingAmount.getText();
            String remaining_payment=txtRemainingAmount.getText();
            String details=txtDetails.getText();

                Payments p1=new Payments(pid, rid, pdate, total_amount, paying_amount, remaining_payment, details);

                if(new PaymentController().updatePayment(p1)){
                    JOptionPane.showMessageDialog(null,"Success");
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Please Insert An PID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRfreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfreshActionPerformed
        try {
            List<Payments> SubjectList= new PaymentController().getAllPayments();
            DefaultTableModel modal=(DefaultTableModel) jtblPayment.getModel();
            modal.setRowCount(0);
            for(Payments sub:SubjectList){
                Object[] rowData={
                    sub.getPid(),
                    sub.getRid(),
                    sub.getPdate(),
                    sub.getTotal_amount(),
                    sub.getPaying_amount(),
                    sub.getRemaining_payment(),
                    sub.getDetail()};
                modal.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtRfreshActionPerformed

    private void txtPayingAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayingAmountActionPerformed
     
  
    }//GEN-LAST:event_txtPayingAmountActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        String id=txtPid.getText();
        double pay = Double.parseDouble(txtPayingAmount.getText());
        double balance=Double.parseDouble(txtTotalAmount.getText());
        double balance1=balance-pay;
        txtRemainingAmount.setText(balance1+"");
    }//GEN-LAST:event_btnpayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpay;
    private javax.swing.JComboBox<String> cmbRid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblPayment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtPayingAmount;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtRemainingAmount;
    private javax.swing.JButton txtRfresh;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

    private void loadREGID() {
       try {
            ArrayList<Registration> AllCourses=RegistrationController.getAllRegistrations();
            for(Registration reg:AllCourses){
                cmbRid.addItem(reg.getRid());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String formatDate(Date date) {
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }

    private void genaratePid() {
        try {
            String PID = PaymentController.generatePID();
            txtPid.setText(PID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllPayments() {
     try {
            List<Payments> List= new PaymentController().getAllPayments();
            DefaultTableModel modal=(DefaultTableModel)jtblPayment.getModel();
            for(Payments temp:List){
                
                modal.addRow(new Object[]{
                    
                  temp.getPid(),
                  temp.getRid(),
                  temp.getPdate(),
                  temp.getTotal_amount(),
                  temp.getPaying_amount(),
                  temp.getRemaining_payment(),
                  temp.getDetail(),
                    
                
                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
