/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Sms.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Sms.Controller.SubjectController;
import lk.ijse.Sms.Modal.Subject;

/**
 *
 * @author Rukz
 */
public class AddSubjects extends javax.swing.JPanel {

    /**
     * Creates new form AddSubjects
     */
    public AddSubjects() {
        initComponents();
        genarateSubid();
        loadAllSubjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtSubID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSubName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSubject = new javax.swing.JTable();
        txtRfresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SUBID  (Subject ID)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 30));

        txtSubID.setBackground(java.awt.Color.white);
        txtSubID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSubID.setForeground(new java.awt.Color(0, 0, 0));
        txtSubID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubIDActionPerformed(evt);
            }
        });
        add(txtSubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 40));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SUBJECT  NAME");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 30));

        txtSubName.setBackground(java.awt.Color.white);
        txtSubName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSubName.setForeground(new java.awt.Color(0, 0, 0));
        add(txtSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 40));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 130, 40));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 130, 40));

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 130, 40));

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Add Subject");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 260, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        jtblSubject.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblSubject);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 160));

        txtRfresh.setBackground(new java.awt.Color(211, 84, 0));
        txtRfresh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRfresh.setForeground(new java.awt.Color(0, 0, 0));
        txtRfresh.setText("REFRESH");
        txtRfresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfreshActionPerformed(evt);
            }
        });
        add(txtRfresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 110, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-ok-50.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 50, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-delete-50.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 50, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-synchronize-45.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            
           String subid=txtSubID.getText();
           String sub_name=txtSubName.getText();

            
            
              Subject s1=new Subject(subid, sub_name);

            boolean isSaved ;
            
                isSaved = new SubjectController().saveSubject(s1);
             
                
           

            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved");
            }else{
                JOptionPane.showMessageDialog(null,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtSubID.getText().trim().length()>0){

            try {
                if(new SubjectController().dropSubject(txtSubID.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Deleted");
                }else{
                    JOptionPane.showMessageDialog(null,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please insert an SID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSubIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubIDActionPerformed
        if(txtSubID.getText().trim().length()>0){
            try {
              
                Subject OBj;
                OBj = new SubjectController().getSubject(txtSubID.getText().trim());

                if(OBj!=null){

                     txtSubName.setText(OBj.getSub_name());
                     

                }else{
                    JOptionPane.showMessageDialog(this,"No Results Fount","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSubIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txtSubID.getText().trim().length()>0){
            try {
               
                String bid=txtSubID.getText();
                 String sub_name=txtSubName.getText();
                

                 Subject s1 =new Subject(bid, sub_name);

                if(new SubjectController().updatesubject(s1)){
                    JOptionPane.showMessageDialog(null,"Success");
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Please Insert An SID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRfreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfreshActionPerformed
        try {
            List<Subject> SubjectList= new SubjectController().getAllSubject();
            DefaultTableModel modal=(DefaultTableModel) jtblSubject.getModel();
            modal.setRowCount(0);
            for(Subject sub:SubjectList){
                Object[] rowData={
                    sub.getSubid(),
                    sub.getSub_name()};
                        modal.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_txtRfreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblSubject;
    private javax.swing.JButton txtRfresh;
    private javax.swing.JTextField txtSubID;
    private javax.swing.JTextField txtSubName;
    // End of variables declaration//GEN-END:variables

    private void genarateSubid() {
        try {
            String subid = SubjectController.generatesubid();
            txtSubID.setText(subid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }   

    private void loadAllSubjects() {
        try {
            List<Subject> SubjectList= new SubjectController().getAllSubject();
            DefaultTableModel modal=(DefaultTableModel)jtblSubject.getModel();
            for(Subject tempSubject:SubjectList){
                
                modal.addRow(new Object[]{
                    
                    tempSubject.getSubid(),
                    tempSubject.getSub_name(),
                    
                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
