/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Sms.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Sms.Controller.CoursesController;
import lk.ijse.Sms.Controller.SemesterController;
import lk.ijse.Sms.Controller.SubjectController;
import lk.ijse.Sms.Modal.Courses;
import lk.ijse.Sms.Modal.Semester;
import lk.ijse.Sms.Modal.Subject;

/**
 *
 * @author Rukz
 */
public class AddSemester extends javax.swing.JPanel {

    /**
     * Creates new form AddSemester
     */
    public AddSemester() {
        initComponents();
        genarateSemid();
        loadCourseID();
        loadSubjectID();
        loadAllSemester();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSemID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCid = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbSbid = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtsemname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSemester = new javax.swing.JTable();
        txtRfresh3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CID  (Course ID)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 120, 30));

        txtSemID.setBackground(java.awt.Color.white);
        txtSemID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSemID.setForeground(new java.awt.Color(0, 0, 0));
        txtSemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemIDActionPerformed(evt);
            }
        });
        add(txtSemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 40));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SEMID  (Semester ID)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        cmbCid.setBackground(java.awt.Color.white);
        cmbCid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbCid.setForeground(new java.awt.Color(0, 0, 0));
        add(cmbCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 40));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SUBID  (Subject ID)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        cmbSbid.setBackground(java.awt.Color.white);
        cmbSbid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbSbid.setForeground(new java.awt.Color(0, 0, 0));
        add(cmbSbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 40));

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 130, 40));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 130, 40));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 130, 40));

        txtsemname.setBackground(java.awt.Color.white);
        txtsemname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtsemname.setForeground(new java.awt.Color(0, 0, 0));
        add(txtsemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 230, 40));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SEMESTER NAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, 30));

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Add  Semester");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 260, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 40));

        jtblSemester.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtblSemester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester ID", "Course ID", "Subject ID", "Semester Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblSemester);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 510, 200));

        txtRfresh3.setBackground(new java.awt.Color(211, 84, 0));
        txtRfresh3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRfresh3.setForeground(new java.awt.Color(0, 0, 0));
        txtRfresh3.setText("REFRESH");
        txtRfresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfresh3ActionPerformed(evt);
            }
        });
        add(txtRfresh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 110, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-ok-50.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 50, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-delete-50.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 50, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-synchronize-45.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            
            String sid=txtSemID.getText();
            String cid= cmbCid.getSelectedItem().toString();
             String subid= cmbSbid.getSelectedItem().toString();
           String semname=txtsemname.getText();
             

           Semester s1=new Semester(subid, cid, subid, semname);
           
            
            boolean isSaved=new SemesterController().saveSemester(s1);
            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved");
            }else{
                JOptionPane.showMessageDialog(null,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemIDActionPerformed
        if(txtSemID.getText().trim().length()>0){
            try {
              
                Semester OBj;
                OBj = new SemesterController().getSemester(txtSemID.getText().trim());

                if(OBj!=null){
                    
                     
                     cmbCid.setSelectedItem(OBj.getCid());
                     cmbSbid.setSelectedItem(OBj.getSubid());
                     txtsemname.setText(OBj.getSem_name());

                     

                }else{
                    JOptionPane.showMessageDialog(this,"No Results Fount","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSemIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(txtSemID.getText().trim().length()>0){

            try {
                if(new SemesterController().dropSemester(txtSemID.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Deleted");
                }else{
                    JOptionPane.showMessageDialog(null,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please insert an TID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txtSemID.getText().trim().length()>0){
            try {
                
                String semid=txtSemID.getText();
                String cid=cmbCid.getSelectedItem().toString();
                String subid=cmbSbid.getSelectedItem().toString();
                String semname=txtsemname.getText();
                
                Semester s1=new Semester(semid, cid, subid, semname);
               

                if(new SemesterController().updateSemester(s1)){
                    JOptionPane.showMessageDialog(null,"Success");
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Please Insert An BID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRfresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfresh3ActionPerformed
        try {
            List<Semester> SubjectList= new SemesterController().getAllSemester();
            DefaultTableModel modal=(DefaultTableModel) jtblSemester.getModel();
            modal.setRowCount(0);
            for(Semester sub:SubjectList){
                Object[] rowData={
                    sub.getSemid(),
                    sub.getCid(),
                    sub.getSubid(),
                    sub.getSem_name()};

                modal.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtRfresh3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCid;
    private javax.swing.JComboBox<String> cmbSbid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblSemester;
    private javax.swing.JButton txtRfresh3;
    private javax.swing.JTextField txtSemID;
    private javax.swing.JTextField txtsemname;
    // End of variables declaration//GEN-END:variables

   

    private void genarateSemid() {
    try {
            String Semid = SemesterController.generatesemid();
            txtSemID.setText(Semid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadCourseID() {
       try {
            ArrayList<Courses> AllCourses=CoursesController.getAllCourses();
            for(Courses course:AllCourses){
                cmbCid.addItem(course.getCid());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSubjectID() {
       try {
            ArrayList<Subject> AllSubjects=SubjectController.getAllSubjects();
            for(Subject sub:AllSubjects){
                cmbSbid.addItem(sub.getSubid());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddBatches.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllSemester() {
        try {
            List<Semester> SemesterList= new SemesterController().getAllSemester();
            DefaultTableModel modal=(DefaultTableModel)jtblSemester.getModel();
            for(Semester tempSemester:SemesterList){
                
                modal.addRow(new Object[]{
                    
                    tempSemester.getSemid(),
                    tempSemester.getCid(),
                    tempSemester.getSubid(),
                    tempSemester.getSem_name(),
                    
                
                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSemester.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSemester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
