/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Sms.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Sms.Controller.StudentController;
import lk.ijse.Sms.Controller.TotalStudentController;
import lk.ijse.Sms.Modal.Student;

/**
 *
 * @author Rukz
 */
public class StudentManage extends javax.swing.JPanel {

    /**
     * Creates new form StudentManage
     */
    public StudentManage() {
        initComponents();
        genarateSID();
        loadAllStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtRfresh3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 240, 241));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(896, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSid.setBackground(java.awt.Color.white);
        txtSid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSid.setForeground(new java.awt.Color(51, 51, 51));
        txtSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSidActionPerformed(evt);
            }
        });
        txtSid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSidKeyPressed(evt);
            }
        });
        add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FIRST NAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        txtFname.setBackground(java.awt.Color.white);
        txtFname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtFname.setForeground(new java.awt.Color(51, 51, 51));
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LAST NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 20));

        txtLname.setBackground(java.awt.Color.white);
        txtLname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtLname.setForeground(new java.awt.Color(51, 51, 51));
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 240, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ADDRESS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        txtAddress.setBackground(java.awt.Color.white);
        txtAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(51, 51, 51));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 520, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NIC");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, -1));

        txtNic.setBackground(java.awt.Color.white);
        txtNic.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNic.setForeground(new java.awt.Color(51, 51, 51));
        add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("BIRTHDAY");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 80, -1));

        txtBirthday.setBackground(java.awt.Color.white);
        txtBirthday.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBirthday.setForeground(new java.awt.Color(51, 51, 51));
        txtBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthdayActionPerformed(evt);
            }
        });
        add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 220, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TELEPHONE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        txtTp.setBackground(java.awt.Color.white);
        txtTp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTp.setForeground(new java.awt.Color(51, 51, 51));
        add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("GENDER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 80, 20));

        cmbGender.setBackground(java.awt.Color.white);
        cmbGender.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbGender.setForeground(java.awt.Color.black);
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });
        add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 220, 40));

        btnSave.setBackground(new java.awt.Color(46, 204, 113));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setForeground(java.awt.Color.black);
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 120, 40));

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(java.awt.Color.black);
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 120, 40));

        btnUpdate.setBackground(new java.awt.Color(41, 128, 185));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("   UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 120, 40));

        jPanel1.setBackground(new java.awt.Color(155, 89, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Students Manage");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        jTable1.setBackground(java.awt.Color.white);
        jTable1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sid", "FirstName", "LastName", "Address", "Nic", "Contact", "Birthday", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 960, 190));

        txtRfresh3.setBackground(new java.awt.Color(211, 84, 0));
        txtRfresh3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRfresh3.setForeground(new java.awt.Color(0, 0, 0));
        txtRfresh3.setText("REFRESH");
        txtRfresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfresh3ActionPerformed(evt);
            }
        });
        add(txtRfresh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 110, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-ok-50.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 50, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-delete-50.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 50, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Sms/view/icons8-synchronize-45.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSidActionPerformed

        if(txtSid.getText().trim().length()>0){
            try {
                Student OBj=new StudentController().getStudent(txtSid.getText().trim());

                if(OBj!=null){
                    txtFname.setText(OBj.getFname());
                    txtLname.setText(OBj.getLname());
                    txtAddress.setText(OBj.getAddress());
                    txtNic.setText(OBj.getNic());
                    txtTp.setText(OBj.getContact_num());
                    txtBirthday.setText(OBj.getDob());
                    cmbGender.setSelectedItem(OBj.getGender());

                }else{
                    JOptionPane.showMessageDialog(this,"No Results Fount","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtSidActionPerformed

    private void txtSidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSidKeyPressed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthdayActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try {
            String sid=txtSid.getText();
            String fname=txtFname.getText();
            String lname=txtLname.getText();
            String address=txtAddress.getText();
            String nic=txtNic.getText();
            String contact_num=txtTp.getText();
            String dob=txtBirthday.getText();
            String gender=cmbGender.getSelectedItem().toString();

            Student s1=new Student(sid, fname, lname, address, nic, contact_num, dob, gender);

            boolean isSaved ;
            
                isSaved = new StudentController().saveStudent(s1);
             
                
           

            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved");
            }else{
                JOptionPane.showMessageDialog(null,"Try Again","Error",JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(txtSid.getText().trim().length()>0){

            try {
                if(new StudentController().dropStudent(txtSid.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Deleted");
                }else{
                    JOptionPane.showMessageDialog(null,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please insert an SID","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if(txtSid.getText().trim().length()>0){
            try {
                String sid=txtSid.getText();
                String fname=txtFname.getText();
                String lname=txtLname.getText();
                String address=txtAddress.getText();
                String nic=txtNic.getText();
                String contact_num=txtTp.getText();
                String dob=txtBirthday.getText();
                String gender=cmbGender.getSelectedItem().toString();

                Student s1=new Student(sid, fname, lname, address, nic, contact_num, dob, gender);

                if(new StudentController().updateState(s1)){
                    JOptionPane.showMessageDialog(null,"Success");
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Please Insert An SID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtRfresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfresh3ActionPerformed
        try {
            List<Student> SubjectList= new StudentController().getAllStudents();
            DefaultTableModel modal=(DefaultTableModel) jTable1.getModel();
            modal.setRowCount(0);
            for(Student sub:SubjectList){
                Object[] rowData={
                    sub.getSid(),
                    sub.getFname(),
                    sub.getLname(),
                    sub.getAddress(),
                    sub.getNic(),
                    sub.getContact_num(),
                    sub.getDob(),
                    sub.getGender()};
                    
                modal.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtRfresh3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNic;
    private javax.swing.JButton txtRfresh3;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtTp;
    // End of variables declaration//GEN-END:variables

    private void genarateSID() {
       try {
            String sid = StudentController.generatereSID();
            txtSid.setText(sid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCourses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllStudent() {
       
            
        try {
            List<Student> StudentList=new TotalStudentController().getAllStudents();
            DefaultTableModel modal=(DefaultTableModel)jTable1.getModel();
            
            for(Student tempStudent:StudentList){
                
                modal.addRow(new Object[]{
                
                    tempStudent.getSid(),
                    tempStudent.getFname(),
                    tempStudent.getLname(),
                    tempStudent.getAddress(),
                    tempStudent.getNic(),
                    tempStudent.getContact_num(),
                    tempStudent.getDob(),
                    tempStudent.getGender(),
                
                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentManage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }
   
}
